// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj6dnL55CeKBvcWVaTYJiWohp25z9J-Ko',
    appId: '1:698452019241:web:87289b6481f5faa8c6f438',
    messagingSenderId: '698452019241',
    projectId: 'itsm2024loginsdk',
    authDomain: 'itsm2024loginsdk.firebaseapp.com',
    storageBucket: 'itsm2024loginsdk.appspot.com',
    measurementId: 'G-J9Q874N827',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFgisKAVvTiXhPwfAbrJdNVRfexh6cfk',
    appId: '1:698452019241:android:412cec17172b82a7c6f438',
    messagingSenderId: '698452019241',
    projectId: 'itsm2024loginsdk',
    storageBucket: 'itsm2024loginsdk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuR8jFLmsg1HkO4KYOSqlLUJROwvZxwAY',
    appId: '1:698452019241:ios:02af0c221a6de3b1c6f438',
    messagingSenderId: '698452019241',
    projectId: 'itsm2024loginsdk',
    storageBucket: 'itsm2024loginsdk.appspot.com',
    iosBundleId: 'com.example.loginsdk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuR8jFLmsg1HkO4KYOSqlLUJROwvZxwAY',
    appId: '1:698452019241:ios:50f4cce9c9d6964ac6f438',
    messagingSenderId: '698452019241',
    projectId: 'itsm2024loginsdk',
    storageBucket: 'itsm2024loginsdk.appspot.com',
    iosBundleId: 'com.example.loginsdk.RunnerTests',
  );
}
